apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ template "harbor.core" . }}-push-secret
  namespace: {{ .Release.Namespace | quote }}
spec:
  data:
  - conversionStrategy: None
    match:
      remoteRef:
        property: registry_password
        remoteKey: secret/{{ .Release.Namespace }}
      secretKey: password
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
  - kind: ClusterSecretStore
    name: vault-backend
  selector:
    secret:
      name: harbor-admin-password
  updatePolicy: Replace
